export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const CHANGE_FETCH_STATUS = 'CHANGE_FETCH_STATUS';
export const NAME_HEADER = 'NAME_HEADER';
export const SET_RECIPE_IN_PROGRESS = 'SET_RECIPE_IN_PROGRESS';
